title: Gabriel's homepage
description: Gabriel's Home on GitHub Pages
github_username: cunning6423
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one