title: Gabriel's homepage
tagline: Gabriel's Home on GitHub Pages
description: On the home page find Gabriel's posted projects and ideas.
github_username: cunning6423
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

